### PR TITLE
Bumps `{rmarkdown}` minimal version

### PR DESCRIPTION
**Pull request by averissimo**
# Pull Request

Part of https://github.com/insightsengineering/coredev-tasks/issues/546

Necessary bump to overcome a lack of binary on ppm snapshots that causes an error on minimum strategies for `scheduled` workflows.

### CODE REVIEW

**Comment by averissimo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by averissimo** [comment]
`{verdepcheck}` tests pass: https://github.com/insightsengineering/tern.rbmi/actions/runs/9398826258

**Comment by averissimo** [comment]
Problem with `rtables` / `formatter` with error; ` argument "fontspec" is missing, with no default`

Changing this back to draft

**Comment by averissimo** [comment]
All good now. Here's the latest scheduled manual run: https://github.com/insightsengineering/tern.rbmi/actions/runs/9450169161

**Review by m7pr — APPROVED** [review]

**Pull request merged**
